Adding support for expanded property for Fitbit sleeps
aviade/ValidicCSharpWrapper pull request #6
Opened 2017-03-03 21:37 UTC by Uthkarsh

2017-03-03 21:40 UTC, aviade approved these changes

2017-03-04 18:44 UTC, jkrez requested changes

2017-03-04 18:44 UTC, jkrez commented on ValidicCSharp/Model/FitBitModel/FitBitExpandedSleep.cs
> +    public class FitBitExpandedSleep : Sleep
"Fitbit" is one word. Please change the capitalization and lowercase the "B"

2017-03-04 18:44 UTC, jkrez commented on ValidicCSharp/Model/FitBitModel/FitBitExpandedSleep.cs
> +        public Double? minutes_after_wakeup { get; set; }
Please change all the properties to use the same naming scheme as other files in the project: using pascal case and no underscores. Follow the examples in ValidicCSharp/Model/Sleep.cs for exmaple

2017-03-04 18:44 UTC, jkrez commented on ValidicCSharp/ValidicCSharp.csproj
> +    <Compile Include="Model\FitBitModel\FitBitExpandedSleep.cs" />
Please rename "FitBitModel" to "FitbitModel" as "Fitbit" is a single word

2017-03-05 00:07 UTC, Uthkarsh commented on ValidicCSharp/Model/FitBitModel/FitBitExpandedSleep.cs
> +    public class FitBitExpandedSleep : Sleep
Yes, I shall make those changes.

2017-03-05 06:52 UTC, jkrez commented on ValidicCSharp/Model/FitBitModel/FitBitExpandedSleep.cs
> +    public class FitBitExpandedSleep : Sleep
Thanks!

2017-03-05 21:19 UTC, merged

2017-03-06 00:26 UTC, jkrez reviewed
Thanks for doing this!

2017-03-06 02:49 UTC, jkrez commented
I update the directory name. Everything looks good now!

On Sun, Mar 5, 2017 at 1:19 PM, Uthkarsh Satish <notifications@github.com>
wrote:

> Merged #6 <https://github.com/aviade/ValidicCSharpWrapper/pull/6>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/aviade/ValidicCSharpWrapper/pull/6#event-986924753>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA37ZwDg3le0PZSpX02ZJLneew-DSutSks5riybkgaJpZM4MSxkB>
> .
>